Application context
Mikhail-Mikhailenko/bring pull request #4
Opened 2023-01-24 14:52 UTC by Neshyk

2023-01-24 17:03 UTC, ggazila commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +            throw new NoUniqueBeanException();
It would be better to see a descriptive message for exceptions. For example, "No beans found for org.example.service.RandomService"

2023-01-24 20:49 UTC, Mikhail-Mikhailenko reviewed
Also I think we should add log.error when we throw exception

2023-01-24 20:49 UTC, Mikhail-Mikhailenko commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +            return bean;
We can return bean without additional variable. For example:
 `return beanType.cast(constructor.newInstance());`

2023-01-24 20:49 UTC, Mikhail-Mikhailenko commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +    private final String packageName;
This is not package name. It is package path.

2023-01-24 20:49 UTC, Mikhail-Mikhailenko commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +        this.context = new ConcurrentHashMap<>();
We can initialize context map not using contructor: 
`private final Map<String, Object> context = new ConcurrentHashMap<>();`

2023-01-24 20:49 UTC, Mikhail-Mikhailenko commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +            throw new BeanInitializingException();
We should throw exception with descriptive message.

2023-01-24 20:49 UTC, Mikhail-Mikhailenko commented on src/test/java/com.breskul.bring/TestComponent1.java
> +public class TestComponent1 {
We should remove this test class

2023-01-24 20:49 UTC, Mikhail-Mikhailenko commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +                .orElseThrow(NuSuchBeanConstructor::new);
We should add desriptive message in this case too.

2023-01-25 16:24 UTC, ggazila commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +                    throw new NoSuchBeanException("Bean type: " + beanType.getName());
suggested change but I'll approve anyway
`			throw new NoSuchBeanException("No beans found for " + beanType.getName());
`

2023-01-25 16:24 UTC, ggazila commented on src/main/java/com/breskul/bring/AnnotationConfigApplicationContext.java
> +            throw new NoUniqueBeanException("Bean type: " + beanType.getName());
suggested change but I'll approve anyway
`			throw new NoUniqueBeanException("There are %s beans found for %s, expected 1.".formatted(beans.size(), beanType.getName()));
`

2023-01-25 16:25 UTC, ggazila approved these changes
Nice job

2023-01-25 16:55 UTC, ggazila requested changes
could you please remove unused methods?

2023-01-25 18:04 UTC, Mikhail-Mikhailenko approved these changes

2023-01-25 20:08 UTC, merged